---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.23.3-bullseye

inputs:
  - name: dis-search-upstream-stub

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dis-search-upstream-stub/ci/scripts/build.sh
